/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk;

public class IPMapSDKJNI {
  public final static native void IPXGeosCoordinate_x_set(long jarg1, IPXGeosCoordinate jarg1_, double jarg2);
  public final static native double IPXGeosCoordinate_x_get(long jarg1, IPXGeosCoordinate jarg1_);
  public final static native void IPXGeosCoordinate_y_set(long jarg1, IPXGeosCoordinate jarg1_, double jarg2);
  public final static native double IPXGeosCoordinate_y_get(long jarg1, IPXGeosCoordinate jarg1_);
  public final static native long new_IPXGeosCoordinate();
  public final static native void delete_IPXGeosCoordinate(long jarg1);
  public final static native double IPXGeosPoint_getX(long jarg1, IPXGeosPoint jarg1_);
  public final static native double IPXGeosPoint_getY(long jarg1, IPXGeosPoint jarg1_);
  public final static native void delete_IPXGeosPoint(long jarg1);
  public final static native long IPXGeosGeometryFactory_createPoint(long jarg1, IPXGeosGeometryFactory jarg1_, long jarg2, IPXGeosCoordinate jarg2_);
  public final static native long new_IPXGeosGeometryFactory();
  public final static native void delete_IPXGeosGeometryFactory(long jarg1);
  public final static native void delete_IPXGeosLineString(long jarg1);
  public final static native long IPXGeosLineString_getCoordinateN(long jarg1, IPXGeosLineString jarg1_, int jarg2);
  public final static native int IPXGeosLineString_getNumPoints(long jarg1, IPXGeosLineString jarg1_);
  public final static native long IPXGeosLineString_getCoordinate(long jarg1, IPXGeosLineString jarg1_);
  public final static native double IPXGeosLineString_getLength(long jarg1, IPXGeosLineString jarg1_);
  public final static native String md5(String jarg1);
  public final static native String decryptString__SWIG_0(String jarg1);
  public final static native String encryptString__SWIG_0(String jarg1);
  public final static native String decryptFile__SWIG_0(String jarg1);
  public final static native String decryptString__SWIG_1(String jarg1, String jarg2);
  public final static native String encryptString__SWIG_1(String jarg1, String jarg2);
  public final static native void encryptFile(String jarg1, String jarg2, String jarg3);
  public final static native String decryptFile__SWIG_1(String jarg1, String jarg2);
  public final static native boolean checkValidity(String jarg1, String jarg2, String jarg3);
  public final static native String getExpiredDate(String jarg1, String jarg2, String jarg3);
  public final static native long new_IPXRouteNetworkDataset();
  public final static native void delete_IPXRouteNetworkDataset(long jarg1);
  public final static native long IPXRouteNetworkDataset_getShorestPath(long jarg1, IPXRouteNetworkDataset jarg1_, long jarg2, IPXGeosPoint jarg2_, long jarg3, IPXGeosPoint jarg3_);
  public final static native String IPXRouteNetworkDataset_toString(long jarg1, IPXRouteNetworkDataset jarg1_);
  public final static native long new_IPXRouteNetworkDBAdapter(String jarg1);
  public final static native boolean IPXRouteNetworkDBAdapter_open(long jarg1, IPXRouteNetworkDBAdapter jarg1_);
  public final static native boolean IPXRouteNetworkDBAdapter_close(long jarg1, IPXRouteNetworkDBAdapter jarg1_);
  public final static native long IPXRouteNetworkDBAdapter_readRouteNetworkDataset(long jarg1, IPXRouteNetworkDBAdapter jarg1_);
  public final static native void delete_IPXRouteNetworkDBAdapter(long jarg1);
}
