/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk;

class IPMapSDK {
	static String md5(String str) {
		return IPMapSDKJNI.md5(str);
	}

	static String decryptString(String str) {
		return IPMapSDKJNI.decryptString(str);
	}

	static String encryptString(String str) {
		return IPMapSDKJNI.encryptString(str);
	}

	static String decryptFile(String file) {
		return IPMapSDKJNI.decryptFile(file);
	}

}
