/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk;

public class IPMapSDKJNI {
  public final static native String md5(String jarg1);
  public final static native String decryptString__SWIG_0(String jarg1);
  public final static native String encryptString__SWIG_0(String jarg1);
  public final static native String decryptFile__SWIG_0(String jarg1);
  public final static native String decryptString__SWIG_1(String jarg1, String jarg2);
  public final static native String encryptString__SWIG_1(String jarg1, String jarg2);
  public final static native void encryptFile(String jarg1, String jarg2, String jarg3);
  public final static native String decryptFile__SWIG_1(String jarg1, String jarg2);
  public final static native boolean checkValidity(String jarg1, String jarg2, String jarg3);
  public final static native String getExpiredDate(String jarg1, String jarg2, String jarg3);
}
