/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk;

class IPXGeosCoordinate {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected IPXGeosCoordinate(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(IPXGeosCoordinate obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				IPMapSDKJNI.delete_IPXGeosCoordinate(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setX(double value) {
		IPMapSDKJNI.IPXGeosCoordinate_x_set(swigCPtr, this, value);
	}

	public double getX() {
		return IPMapSDKJNI.IPXGeosCoordinate_x_get(swigCPtr, this);
	}

	public void setY(double value) {
		IPMapSDKJNI.IPXGeosCoordinate_y_set(swigCPtr, this, value);
	}

	public double getY() {
		return IPMapSDKJNI.IPXGeosCoordinate_y_get(swigCPtr, this);
	}

	public IPXGeosCoordinate() {
		this(IPMapSDKJNI.new_IPXGeosCoordinate(), true);
	}

}
