/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk;

class IPXGeosGeometryFactory {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected IPXGeosGeometryFactory(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(IPXGeosGeometryFactory obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				IPMapSDKJNI.delete_IPXGeosGeometryFactory(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public IPXGeosPoint createPoint(IPXGeosCoordinate coordinate) {
		long cPtr = IPMapSDKJNI.IPXGeosGeometryFactory_createPoint(swigCPtr,
				this, IPXGeosCoordinate.getCPtr(coordinate), coordinate);
		return (cPtr == 0) ? null : new IPXGeosPoint(cPtr, false);
	}

	public IPXGeosGeometryFactory() {
		this(IPMapSDKJNI.new_IPXGeosGeometryFactory(), true);
	}

}
