/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk;

class IPXRouteNetworkDBAdapter {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected IPXRouteNetworkDBAdapter(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(IPXRouteNetworkDBAdapter obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				IPMapSDKJNI.delete_IPXRouteNetworkDBAdapter(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public IPXRouteNetworkDBAdapter(String dbPath) {
		this(IPMapSDKJNI.new_IPXRouteNetworkDBAdapter(dbPath), true);
	}

	public boolean open() {
		return IPMapSDKJNI.IPXRouteNetworkDBAdapter_open(swigCPtr, this);
	}

	public boolean close() {
		return IPMapSDKJNI.IPXRouteNetworkDBAdapter_close(swigCPtr, this);
	}

	public IPXRouteNetworkDataset readRouteNetworkDataset() {
		long cPtr = IPMapSDKJNI
				.IPXRouteNetworkDBAdapter_readRouteNetworkDataset(swigCPtr,
						this);
		return (cPtr == 0) ? null : new IPXRouteNetworkDataset(cPtr, false);
	}

}
