/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPMapSDK {
  public static String md5(String str) {
    return IPMapSDKJNI.md5(str);
  }

  public static String decryptString(String str) {
    return IPMapSDKJNI.decryptString__SWIG_0(str);
  }

  public static String encryptString(String str) {
    return IPMapSDKJNI.encryptString__SWIG_0(str);
  }

  public static String decryptFile(String file) {
    return IPMapSDKJNI.decryptFile__SWIG_0(file);
  }

  public static String decryptString(String str, String key) {
    return IPMapSDKJNI.decryptString__SWIG_1(str, key);
  }

  public static String encryptString(String originalString, String key) {
    return IPMapSDKJNI.encryptString__SWIG_1(originalString, key);
  }

  public static void encryptFile(String originalPath, String encryptedFile, String key) {
    IPMapSDKJNI.encryptFile(originalPath, encryptedFile, key);
  }

  public static String decryptFile(String file, String key) {
    return IPMapSDKJNI.decryptFile__SWIG_1(file, key);
  }

  public static boolean checkValidity(String userID, String license, String buildingID) {
    return IPMapSDKJNI.checkValidity(userID, license, buildingID);
  }

  public static String getExpiredDate(String userID, String license, String buildingID) {
    return IPMapSDKJNI.getExpiredDate(userID, license, buildingID);
  }

}
