/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPXFeatureRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IPXFeatureRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXFeatureRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_IPXFeatureRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGeometry(IPXGeosGeometry value) {
    IPMapSDKJNI.IPXFeatureRecord_geometry_set(swigCPtr, this, IPXGeosGeometry.getCPtr(value), value);
  }

  public IPXGeosGeometry getGeometry() {
    long cPtr = IPMapSDKJNI.IPXFeatureRecord_geometry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPXGeosGeometry(cPtr, false);
  }

  public void setGeoID(String value) {
    IPMapSDKJNI.IPXFeatureRecord_geoID_set(swigCPtr, this, value);
  }

  public String getGeoID() {
    return IPMapSDKJNI.IPXFeatureRecord_geoID_get(swigCPtr, this);
  }

  public void setPoiID(String value) {
    IPMapSDKJNI.IPXFeatureRecord_poiID_set(swigCPtr, this, value);
  }

  public String getPoiID() {
    return IPMapSDKJNI.IPXFeatureRecord_poiID_get(swigCPtr, this);
  }

  public void setCategoryID(String value) {
    IPMapSDKJNI.IPXFeatureRecord_categoryID_set(swigCPtr, this, value);
  }

  public String getCategoryID() {
    return IPMapSDKJNI.IPXFeatureRecord_categoryID_get(swigCPtr, this);
  }

  public void setName(String value) {
    IPMapSDKJNI.IPXFeatureRecord_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IPMapSDKJNI.IPXFeatureRecord_name_get(swigCPtr, this);
  }

  public void setSymbolID(int value) {
    IPMapSDKJNI.IPXFeatureRecord_symbolID_set(swigCPtr, this, value);
  }

  public int getSymbolID() {
    return IPMapSDKJNI.IPXFeatureRecord_symbolID_get(swigCPtr, this);
  }

  public void setFloorNumber(int value) {
    IPMapSDKJNI.IPXFeatureRecord_floorNumber_set(swigCPtr, this, value);
  }

  public int getFloorNumber() {
    return IPMapSDKJNI.IPXFeatureRecord_floorNumber_get(swigCPtr, this);
  }

  public void setLayer(int value) {
    IPMapSDKJNI.IPXFeatureRecord_layer_set(swigCPtr, this, value);
  }

  public int getLayer() {
    return IPMapSDKJNI.IPXFeatureRecord_layer_get(swigCPtr, this);
  }

  public void setLevelMax(int value) {
    IPMapSDKJNI.IPXFeatureRecord_levelMax_set(swigCPtr, this, value);
  }

  public int getLevelMax() {
    return IPMapSDKJNI.IPXFeatureRecord_levelMax_get(swigCPtr, this);
  }

  public void setLevelMin(int value) {
    IPMapSDKJNI.IPXFeatureRecord_levelMin_set(swigCPtr, this, value);
  }

  public int getLevelMin() {
    return IPMapSDKJNI.IPXFeatureRecord_levelMin_get(swigCPtr, this);
  }

  public IPXFeatureRecord() {
    this(IPMapSDKJNI.new_IPXFeatureRecord(), true);
  }

}
