/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPXGeosPolygon extends IPXGeosGeometry {
  private long swigCPtr;

  protected IPXGeosPolygon(long cPtr, boolean cMemoryOwn) {
    super(IPMapSDKJNI.IPXGeosPolygon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXGeosPolygon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_IPXGeosPolygon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IPXGeosLineString getExteriorRing() {
    long cPtr = IPMapSDKJNI.IPXGeosPolygon_getExteriorRing(swigCPtr, this);
    return (cPtr == 0) ? null : new IPXGeosLineString(cPtr, false);
  }

  public long getNumInteriorRing() {
    return IPMapSDKJNI.IPXGeosPolygon_getNumInteriorRing(swigCPtr, this);
  }

  public IPXGeosLineString getInteriorRingN(long n) {
    long cPtr = IPMapSDKJNI.IPXGeosPolygon_getInteriorRingN(swigCPtr, this, n);
    return (cPtr == 0) ? null : new IPXGeosLineString(cPtr, false);
  }

}
