/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public final class IPXGeosGeometryTypeId {
  public final static IPXGeosGeometryTypeId GEOS_POINT = new IPXGeosGeometryTypeId("GEOS_POINT");
  public final static IPXGeosGeometryTypeId GEOS_LINESTRING = new IPXGeosGeometryTypeId("GEOS_LINESTRING");
  public final static IPXGeosGeometryTypeId GEOS_LINEARRING = new IPXGeosGeometryTypeId("GEOS_LINEARRING");
  public final static IPXGeosGeometryTypeId GEOS_POLYGON = new IPXGeosGeometryTypeId("GEOS_POLYGON");
  public final static IPXGeosGeometryTypeId GEOS_MULTIPOINT = new IPXGeosGeometryTypeId("GEOS_MULTIPOINT");
  public final static IPXGeosGeometryTypeId GEOS_MULTILINESTRING = new IPXGeosGeometryTypeId("GEOS_MULTILINESTRING");
  public final static IPXGeosGeometryTypeId GEOS_MULTIPOLYGON = new IPXGeosGeometryTypeId("GEOS_MULTIPOLYGON");
  public final static IPXGeosGeometryTypeId GEOS_GEOMETRYCOLLECTION = new IPXGeosGeometryTypeId("GEOS_GEOMETRYCOLLECTION");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPXGeosGeometryTypeId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPXGeosGeometryTypeId.class + " with value " + swigValue);
  }

  private IPXGeosGeometryTypeId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPXGeosGeometryTypeId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPXGeosGeometryTypeId(String swigName, IPXGeosGeometryTypeId swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPXGeosGeometryTypeId[] swigValues = { GEOS_POINT, GEOS_LINESTRING, GEOS_LINEARRING, GEOS_POLYGON, GEOS_MULTIPOINT, GEOS_MULTILINESTRING, GEOS_MULTIPOLYGON, GEOS_GEOMETRYCOLLECTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

