/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPXGeosLineString extends IPXGeosGeometry {
  private long swigCPtr;

  protected IPXGeosLineString(long cPtr, boolean cMemoryOwn) {
    super(IPMapSDKJNI.IPXGeosLineString_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXGeosLineString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_IPXGeosLineString(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IPXGeosCoordinate getCoordinateN(int n) {
    return new IPXGeosCoordinate(IPMapSDKJNI.IPXGeosLineString_getCoordinateN(swigCPtr, this, n), false);
  }

  public long getNumPoints() {
    return IPMapSDKJNI.IPXGeosLineString_getNumPoints(swigCPtr, this);
  }

  public IPXGeosCoordinate getCoordinate() {
    long cPtr = IPMapSDKJNI.IPXGeosLineString_getCoordinate(swigCPtr, this);
    return (cPtr == 0) ? null : new IPXGeosCoordinate(cPtr, false);
  }

  public double getLength() {
    return IPMapSDKJNI.IPXGeosLineString_getLength(swigCPtr, this);
  }

}
