/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPXGeosGeometry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IPXGeosGeometry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXGeosGeometry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_IPXGeosGeometry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IPXGeosGeometryTypeId getGeometryTypeId() {
    return IPXGeosGeometryTypeId.swigToEnum(IPMapSDKJNI.IPXGeosGeometry_getGeometryTypeId(swigCPtr, this));
  }

}
