/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPXMapDataDBAdapter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IPXMapDataDBAdapter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXMapDataDBAdapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_IPXMapDataDBAdapter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IPXMapDataDBAdapter(String dbPath) {
    this(IPMapSDKJNI.new_IPXMapDataDBAdapter(dbPath), true);
  }

  public boolean open() {
    return IPMapSDKJNI.IPXMapDataDBAdapter_open(swigCPtr, this);
  }

  public boolean close() {
    return IPMapSDKJNI.IPXMapDataDBAdapter_close(swigCPtr, this);
  }

  public VectorOfFeatureRecord getAllRecordsOnFloor(int floor) {
    return new VectorOfFeatureRecord(IPMapSDKJNI.IPXMapDataDBAdapter_getAllRecordsOnFloor(swigCPtr, this, floor), true);
  }

}
