/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class IPXRouteNetworkDataset {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IPXRouteNetworkDataset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPXRouteNetworkDataset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_IPXRouteNetworkDataset(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IPXRouteNetworkDataset() {
    this(IPMapSDKJNI.new_IPXRouteNetworkDataset(), true);
  }

  public IPXGeosLineString getShorestPath(IPXGeosPoint start, IPXGeosPoint end) {
    long cPtr = IPMapSDKJNI.IPXRouteNetworkDataset_getShorestPath(swigCPtr, this, IPXGeosPoint.getCPtr(start), start, IPXGeosPoint.getCPtr(end), end);
    return (cPtr == 0) ? null : new IPXGeosLineString(cPtr, false);
  }

  public String toString() {
    return IPMapSDKJNI.IPXRouteNetworkDataset_toString(swigCPtr, this);
  }

}
