/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class TYMapSDKJNI {
  public final static native String md5(String jarg1);
  public final static native String decryptString(String jarg1);
  public final static native String encryptString(String jarg1);
  public final static native String decryptFile(String jarg1);
}
