/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class TYMapSDK {
  public static String md5(String str) {
    return TYMapSDKJNI.md5(str);
  }

  public static String decryptString(String str) {
    return TYMapSDKJNI.decryptString(str);
  }

  public static String encryptString(String str) {
    return TYMapSDKJNI.encryptString(str);
  }

  public static String decryptFile(String file) {
    return TYMapSDKJNI.decryptFile(file);
  }

}
