/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ty.mapsdk.swig;

public class VectorOfFeatureRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfFeatureRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfFeatureRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPMapSDKJNI.delete_VectorOfFeatureRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfFeatureRecord() {
    this(IPMapSDKJNI.new_VectorOfFeatureRecord__SWIG_0(), true);
  }

  public VectorOfFeatureRecord(int n) {
    this(IPMapSDKJNI.new_VectorOfFeatureRecord__SWIG_1(n), true);
  }

  public int size() {
    return IPMapSDKJNI.VectorOfFeatureRecord_size(swigCPtr, this);
  }

  public int capacity() {
    return IPMapSDKJNI.VectorOfFeatureRecord_capacity(swigCPtr, this);
  }

  public void reserve(int n) {
    IPMapSDKJNI.VectorOfFeatureRecord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return IPMapSDKJNI.VectorOfFeatureRecord_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IPMapSDKJNI.VectorOfFeatureRecord_clear(swigCPtr, this);
  }

  public void add(IPXFeatureRecord x) {
    IPMapSDKJNI.VectorOfFeatureRecord_add(swigCPtr, this, IPXFeatureRecord.getCPtr(x), x);
  }

  public IPXFeatureRecord get(int i) {
    long cPtr = IPMapSDKJNI.VectorOfFeatureRecord_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new IPXFeatureRecord(cPtr, false);
  }

  public void set(int i, IPXFeatureRecord val) {
    IPMapSDKJNI.VectorOfFeatureRecord_set(swigCPtr, this, i, IPXFeatureRecord.getCPtr(val), val);
  }

}
